CREATE OR REPLACE FUNCTION TO_TIMESTAMP_NULLABLE(input TEXT, format TEXT)
RETURNS TIMESTAMP AS $$
BEGIN
    RETURN TO_TIMESTAMP(input, format);
EXCEPTION WHEN others THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql IMMUTABLE;
